version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file search-photos.yaml --s3-bucket coms6998hw2-lambda-pipeline-search-photos --output-template-file search-photos.yaml
artifacts:  
  type: zip
  files:
    - search-photos.yaml