AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD HW2 Lambda
Resources:
 LambdaFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: lambda-function
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LambdaCode
      Description: "Lambda function for CD"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::257520041141:role/service-role/codebuild-lambdaProject1-service-role"
      Environment:
        Variables:
          REGION: us-east-1